---
title: "Daily Pup"
author: "Bingo"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r wrap-hook, message=FALSE, warning=FALSE, include=FALSE}
library(jsonlite)
belp <- fromJSON("https://www.reddit.com/r/rarepuppers.json")
titles <- belp$data$children$data$title
urls <- belp$data$children$data$url
#just filter for jpg and png
puppyframe <- data.frame(titles, urls)
puppyframe <- puppyframe[-1, ]
library(data.table)
puppyframe2 <- puppyframe[grepl(".jpg$", puppyframe$urls) | grepl(".png$", puppyframe$urls), ]
idealpup <- puppyframe2[sample(nrow(puppyframe2), 3), ]
img_path1 <- as.character(idealpup[1, 2])
img_path2 <- as.character(idealpup[2, 2])
img_path3 <- as.character(idealpup[3, 2])
img1 <- magick::image_read(img_path1)
img2 <- magick::image_read(img_path2)
img3 <- magick::image_read(img_path3)
par(c(0, 0, 0, 0))
```

```{r echo=FALSE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
# lapply(idealpup$urls, magick::image_read)
knitr::combine_words(idealpup[1, 1])
plot(img1)
knitr::combine_words(idealpup[2, 1])
plot(img2)
knitr::combine_words(idealpup[3, 1])
plot(img3)
```



```{r}
# want to use some loops instead in order to iterate the ideal pupper

```

